fix(rtk): handle closed stdout gracefully (#100)
When the `rtk` command's output is piped to another command that closes
stdout (e.g., `| false`), it previously panicked with a "Broken pipe"
error.

```console
cargo run --package rtk --bin rtk -- eval test_fixtures/golden_envs/inline_env/ | false
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/rtk eval test_fixtures/golden_envs/inline_env/`

thread 'main' panicked at library/std/src/io/stdio.rs:1165:9:
failed printing to stdout: Broken pipe (os error 32)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This change modifies the output handling to catch and ignore such
errors.

To enable this to be tested, we've split the commands out to separate
modules, and introduced a layer of DI. The new tests fail before the fix
and succeed after.

While we're doing that, all the missing subcommands from `tk`
have been added, and the `--help` descriptions copied over. This makes
it easier to compare the two projects.

Finally, `cargo fmt` has been run on the project to ensure consistent
formatting.